apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv
  namespace: crypto-app
  labels:
    app: mysql-pv
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: crypto-app
  labels:
    app: mysql-pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi