apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysqldb
  namespace: crypto-app
  labels:
    app:  mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  mysqldb
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  mysqldb
        image:  mysql:8.0.30
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: crypto-cm
              key: MYSQLDB_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: crypto-cm
              key: MYSQLDB_ROOT_PASSWORD
        ports:
        - containerPort:  3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim: 
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  namespace: crypto-app
spec:
  selector:
    app: mysqldb
  clusterIP: None
  ports:
  - name: mysqldb
    port: 3306
    targetPort: 3306 
