apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-crypto
  namespace: crypto-app
  labels:
    app: frontend-crypto
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-crypto
  template:
    metadata:
      labels:
        app: frontend-crypto
    spec:
      containers:
      - name: frontend-crypto
        image: gabrielobarbosa/crypto:v3
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-crypto
  namespace: crypto-app
spec:
  selector:
    app: frontend-crypto
  type: NodePort
  ports:
  - name: frontend-crypto
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-frontend-crypto
  namespace: crypto-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-crypto
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50


