kind: ConfigMap
apiVersion: v1
metadata:
  name: carteira-crypto-cm
  namespace: crypto-app
data:
  POSTGRES_DB: "carteira-cryptos"
  POSTGRES_HOST: "postgres"
  POSTGRES_USER: "postgres" 
  POSTGRES_PASSWORD: "docker"
  POSTGRES_DOCKER_PORT: "5432"
  PGADMIN_DEFAULT_EMAIL: "pgadmin@email.com"
  PGADMIN_DEFAULT_PASSWORD: "senha"
  COTACAO_API_URL: "http://cotacao-crypto-svc-int:5555/"