kind: ConfigMap
apiVersion: v1
metadata:
  name: carteira-crypto-cm
  namespace: crypto-app
data:
  POSTGRES_DB: "carteira-cryptos"
  POSTGRES_USER: "postgres" 
  POSTGRES_PASSWORD: "docker"
  PGADMIN_DEFAULT_EMAIL: "pgadmin@email.com"
  PGADMIN_DEFAULT_PASSWORD: "senha"

