apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-cotacao-crypto
  namespace: crypto-app
  labels:
    app: cotacao-crypto-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cotacao-crypto-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 40



